"""Regenerate pg_mimic/information_schema.json from a real PostgreSQL server.

    python tools/generate_information_schema.py "host=127.0.0.1 dbname=postgres"

pg_mimic answers information_schema by executing the client's SQL against a
synthesised copy of the views, so it has to declare the columns each view has.
Three things about that list are properties of PostgreSQL rather than of
pg_mimic, and none of them is worth writing down by hand.

*The columns.* `columns` has 44 of them and `tables` 12. Hand-listing is how it
came to carry 7 and 4, and every column left off answered empty rather than
erroring -- see #99.

*Their order.* `SELECT *` has to come back in the server's order, which is
`ordinal_position`, not alphabetical and not the order anyone would think to
type them in.

*Their types.* Not guessable even within one view: in `tables`, `table_catalog`
is `name` while `table_type` is `character varying`.

The *values* are not here. Those are a property of the session's schema() and
live in pg_mimic.catalog, which fills in what it can derive and NULLs the rest.

Which views to emit is an argument, defaulting to the ones pg_mimic populates:

    python tools/generate_information_schema.py "<dsn>" tables columns

Postgres has 69 information_schema views and this deliberately does not dump
them all. A view with a shape but no populator is a query that runs and returns
nothing, which is the bug this file exists to fix rather than to spread.
"""

from __future__ import annotations

import json
import pathlib
import sys

_DEFAULT_VIEWS = ("tables", "columns")


def _columns_of(cursor, view: str) -> list[dict]:
    """The view's columns in ordinal_position order, with the type of each."""
    cursor.execute(
        """
        SELECT column_name, data_type
        FROM information_schema.columns
        WHERE table_schema = 'information_schema' AND table_name = %s
        ORDER BY ordinal_position
        """,
        (view,),
    )
    rows = cursor.fetchall()
    if not rows:
        raise SystemExit(f"no such information_schema view: {view}")
    return [{"name": name, "data_type": data_type} for name, data_type in rows]


def _verify(cursor, view: str, columns: list[dict]) -> None:
    """Prove the captured order is the order `SELECT *` actually comes back in.

    ordinal_position is what the catalog is being generated from, but it is not
    self-evidently the same thing as the result order of a star -- and matching
    that star is the whole point. The server settles it: ask for one and compare.
    """
    cursor.execute(f"SELECT * FROM information_schema.{view} LIMIT 0")
    served = [description.name for description in cursor.description]
    ours = [column["name"] for column in columns]
    if served != ours:
        for position, (theirs, mine) in enumerate(zip(served, ours), start=1):
            if theirs != mine:
                print(f"  MISMATCH {view} position {position}: server {theirs!r}, ours {mine!r}", file=sys.stderr)
        raise SystemExit(f"captured order for {view} is not the order SELECT * returns")
    print(f"  {view}: {len(ours)} columns, in the order SELECT * returns them")


def _render_document(document: dict) -> str:
    """One line per column, rather than json.dumps's one line per *field*.

    A regenerated file then diffs as the columns that changed between releases,
    instead of as several hundred lines of re-indented punctuation.
    """
    views = document["views"]
    lines = ["{"]
    for key in ("_comment", "_generated_from"):
        lines.append(f" {json.dumps(key)}: {json.dumps(document[key])},")
    lines.append(' "views": {')
    last_view = len(views) - 1
    for view_index, (view, columns) in enumerate(views.items()):
        lines.append(f"  {json.dumps(view)}: [")
        last_column = len(columns) - 1
        for index, column in enumerate(columns):
            comma = "" if index == last_column else ","
            lines.append(f"   {json.dumps(column, separators=(', ', ': '))}{comma}")
        lines.append("  ]" + ("" if view_index == last_view else ","))
    lines += [" }", "}"]
    return "\n".join(lines) + "\n"


def main(dsn: str, view_names: list[str]) -> None:
    import psycopg

    with psycopg.connect(dsn) as connection, connection.cursor() as cursor:
        cursor.execute("SELECT current_setting('server_version')")
        # "18.4 (Homebrew)" -- the build tag is the packager's, not PostgreSQL's.
        server_version = cursor.fetchone()[0].split()[0]
        views = {}
        for view in view_names:
            views[view] = _columns_of(cursor, view)
            _verify(cursor, view, views[view])

    document = {
        "_comment": "Generated by tools/generate_information_schema.py -- do not edit by hand.",
        "_generated_from": f"PostgreSQL {server_version}",
        "views": views,
    }
    target = pathlib.Path(__file__).resolve().parent.parent / "pg_mimic" / "information_schema.json"
    target.write_text(_render_document(document))
    print(f"  wrote {sum(len(columns) for columns in views.values())} columns across {len(views)} views to {target}")


if __name__ == "__main__":
    main(sys.argv[1] if len(sys.argv) > 1 else "", sys.argv[2:] or list(_DEFAULT_VIEWS))
